name: build and test

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Avoid pre-populating the NuGet package cache

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore src/dbup-cli.sln
        
      - name: Run unit tests
        run: dotnet test ./src/dbup-cli.tests --no-restore --collect:"XPlat Code Coverage"

      - name: Run integration tests
        run: dotnet test ./src/dbup-cli.integration-tests --no-restore --collect:"XPlat Code Coverage"