name: publish nuget package

on:
  push:
    tags:
      - "v*.*.*" # Trigger on semantic versioning tags, e.g., v1.0.0

jobs:
  build-and-test:
    # uses: drewburlingame/dotnet-cli/.github/workflows/build_and_test.yml@main
    uses: ./.github/workflows/build_and_test.yml
    
  publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
      # Extract version from tag (e.g., v1.2.3 -> 1.2.3)
      - name: Extract version from tag
        id: extract_version
        run: echo "##[set-output name=VERSION;]${GITHUB_REF/refs\/tags\/v/}"
        shell: bash

      # Pack NuGet package
      - name: Pack NuGet package
        run: |
          dotnet pack src/dbup-cli/dbup-cli.csproj \
            --configuration Release \
            /p:PackageVersion=${{ steps.extract_version.outputs.VERSION }} \
            /p:ContinuousIntegrationBuild=true

      # Publish the package to NuGet.org
      - name: Publish NuGet Package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push ./src/dbup-cli/nupkg/*.nupkg \
            --api-key $NUGET_API_KEY \
            --source "https://api.nuget.org/v3/index.json"

      # Create a GitHub release
      - name: Create GitHub Release
        uses: elgohr/Github-Release-Action@v5
        with:
          tag: ${{ github.ref_name }} # The tag, e.g. v1.0.0
          title: Release ${{ github.ref_name }}
          body: |
            ## What’s Changed
            See the [changelog](https://github.com/drewburlingame/dbup-cli/releases/tag/${{ github.ref_name }}).
          draft: true
          prerelease: ${{ contains(env.VERSION, '-') || github.ref != 'refs/heads/master' }} # Mark as prerelease if not master branch or contains '-'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}